// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpNUg-BLh4Fs0F-o8QCFi6zMmUQflZph8',
    appId: '1:41846645232:web:613b2d88a64e2047e57d35',
    messagingSenderId: '41846645232',
    projectId: 'project-cloud-messaging-5aea7',
    authDomain: 'project-cloud-messaging-5aea7.firebaseapp.com',
    storageBucket: 'project-cloud-messaging-5aea7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8oCmy6u1yHmR1_2U-Tg4yDAs-Sn7kXS4',
    appId: '1:41846645232:android:372d8d9b94dae764e57d35',
    messagingSenderId: '41846645232',
    projectId: 'project-cloud-messaging-5aea7',
    storageBucket: 'project-cloud-messaging-5aea7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANGxL_Rtk6mH5ut6PC4MTctrnNCgoeihI',
    appId: '1:41846645232:ios:e158f51acd1bc603e57d35',
    messagingSenderId: '41846645232',
    projectId: 'project-cloud-messaging-5aea7',
    storageBucket: 'project-cloud-messaging-5aea7.appspot.com',
    iosClientId: '41846645232-0hitq20qulpo8usffnfrn7f7r8o950j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCloudMessaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANGxL_Rtk6mH5ut6PC4MTctrnNCgoeihI',
    appId: '1:41846645232:ios:e158f51acd1bc603e57d35',
    messagingSenderId: '41846645232',
    projectId: 'project-cloud-messaging-5aea7',
    storageBucket: 'project-cloud-messaging-5aea7.appspot.com',
    iosClientId: '41846645232-0hitq20qulpo8usffnfrn7f7r8o950j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCloudMessaging',
  );
}