// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJBriaLTCV6JLFCcSrqavFW-dPbp-kwXM',
    appId: '1:656870791054:web:795c2ec7eef34c12a3b6df',
    messagingSenderId: '656870791054',
    projectId: 'fcmtest-252e8',
    authDomain: 'fcmtest-252e8.firebaseapp.com',
    storageBucket: 'fcmtest-252e8.appspot.com',
    measurementId: 'G-9QEN3B8K7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu6aUyJgAp3Zq1aFRK32AvfBkaHtGWCXA',
    appId: '1:656870791054:android:29b8899966ffc66fa3b6df',
    messagingSenderId: '656870791054',
    projectId: 'fcmtest-252e8',
    storageBucket: 'fcmtest-252e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMEMFvzzwpaWVaSmNneYV-lcyHxaI7kKI',
    appId: '1:656870791054:ios:ec398ff7a7ef3967a3b6df',
    messagingSenderId: '656870791054',
    projectId: 'fcmtest-252e8',
    storageBucket: 'fcmtest-252e8.appspot.com',
    iosClientId: '656870791054-up2i89u0f4pe49sinigo7rdu044p02f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcmtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMEMFvzzwpaWVaSmNneYV-lcyHxaI7kKI',
    appId: '1:656870791054:ios:ec398ff7a7ef3967a3b6df',
    messagingSenderId: '656870791054',
    projectId: 'fcmtest-252e8',
    storageBucket: 'fcmtest-252e8.appspot.com',
    iosClientId: '656870791054-up2i89u0f4pe49sinigo7rdu044p02f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcmtest',
  );
}
